version: 2
jobs:
  build:
    working_directory: /go/src/github.com/openfresh/plasma
    docker:
      - image: openfresh/golang:latest 
      - image: redis:3.2.9-alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
          reusable: true
      - run:
          name: install Docker clinet
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: deps
          command: make deps 
      - run:
          name: test
          command: make test
      - run:
          name: go build
          command: make build
      - run:
          name: docker build
          command: docker build -t openfresh/plasma:latest .
      - run:
          name: release latest
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push openfresh/plasma:latest 
              fi
